/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;

import client.Client;
import client.DbDownload;
import client.ServerData;
import helpclasses.CommEnum;
import helpclasses.CommMessage;
import helpclasses.Farm;
import helpclasses.Message;
import helpclasses.Owner;
import helpclasses.Sheep;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author Kyrre
 */
public class Hub extends javax.swing.JFrame {

    /**
     * Creates new form Hub
     */
    public Hub() {
        initComponents();
        //initJPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        panelHome = new javax.swing.JPanel();
        tabHome = new javax.swing.JTabbedPane();
        messages = new javax.swing.JPanel();
        messageList = new javax.swing.JList();
        map = new javax.swing.JPanel();
        panelFilters = new javax.swing.JPanel();
        filtersLabel = new javax.swing.JLabel();
        filtersFarmComboBox = new javax.swing.JComboBox();
        filtersFarmLabel = new javax.swing.JLabel();
        filtersSheepLabel = new javax.swing.JLabel();
        filtersSheepComboBox = new javax.swing.JComboBox();
        filtersAlarmCheckBox = new javax.swing.JCheckBox();
        filtersAlarmLabel = new javax.swing.JLabel();
        filtersFilterButton = new javax.swing.JButton();
        tabOptions = new javax.swing.JTabbedPane();
        addSheep = new javax.swing.JPanel();
        addSheepTitleLabel = new javax.swing.JLabel();
        addSheepName = new javax.swing.JTextField();
        addSheepNameLabel = new javax.swing.JLabel();
        addSheepBirthYearLabel = new javax.swing.JLabel();
        addSheepFarm = new javax.swing.JComboBox();
        addSheepFarmLabel = new javax.swing.JLabel();
        addSheepBirthYear = new javax.swing.JComboBox();
        addSheepNameOptionalLabel = new javax.swing.JLabel();
        addSheepAdd = new javax.swing.JButton();
        removeSheep = new javax.swing.JPanel();
        removeSheepTitleLabel = new javax.swing.JLabel();
        removeSheepID = new javax.swing.JTextField();
        removeSheepIDLabel = new javax.swing.JLabel();
        removeSheepRemove = new javax.swing.JButton();
        addFarm = new javax.swing.JPanel();
        addFarmTitleLabel = new javax.swing.JLabel();
        addFarmName = new javax.swing.JTextField();
        addFarmNameLabel = new javax.swing.JLabel();
        addFarmAdd = new javax.swing.JButton();
        removeFarm = new javax.swing.JPanel();
        removeFarmTitleLabel = new javax.swing.JLabel();
        removeFarmNameLabel = new javax.swing.JLabel();
        removeFarmAdd = new javax.swing.JButton();
        removeFarmComboFarm = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelHome.setName("panelHome"); // NOI18N

        tabHome.setPreferredSize(new java.awt.Dimension(800, 600));
        tabHome.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabHomeStateChanged(evt);
            }
        });

        messageList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });

        javax.swing.GroupLayout messagesLayout = new javax.swing.GroupLayout(messages);
        messages.setLayout(messagesLayout);
        messagesLayout.setHorizontalGroup(
            messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageList, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        messagesLayout.setVerticalGroup(
            messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageList, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabHome.addTab("Messages", messages);

        javax.swing.GroupLayout mapLayout = new javax.swing.GroupLayout(map);
        map.setLayout(mapLayout);
        mapLayout.setHorizontalGroup(
            mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        mapLayout.setVerticalGroup(
            mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        tabHome.addTab("Map", map);

        filtersLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        filtersLabel.setText("Filters:");

        filtersFarmComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Farms" }));

        filtersFarmLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        filtersFarmLabel.setText("Farm:");

        filtersSheepLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        filtersSheepLabel.setText("Sheep:");

        filtersSheepComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Sheep" }));

        filtersAlarmCheckBox.setText("Only alarm messages.");
        filtersAlarmCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtersAlarmCheckBoxActionPerformed(evt);
            }
        });

        filtersAlarmLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        filtersAlarmLabel.setText("Alarm:");

        filtersFilterButton.setText("Filter");
        filtersFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtersFilterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFiltersLayout = new javax.swing.GroupLayout(panelFilters);
        panelFilters.setLayout(panelFiltersLayout);
        panelFiltersLayout.setHorizontalGroup(
            panelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filtersFarmComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filtersSheepComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFiltersLayout.createSequentialGroup()
                        .addGroup(panelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filtersLabel)
                            .addComponent(filtersFarmLabel)
                            .addComponent(filtersSheepLabel)
                            .addComponent(filtersAlarmLabel)
                            .addComponent(filtersAlarmCheckBox)
                            .addComponent(filtersFilterButton))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFiltersLayout.setVerticalGroup(
            panelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltersLayout.createSequentialGroup()
                .addComponent(filtersLabel)
                .addGap(46, 46, 46)
                .addComponent(filtersFarmLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtersFarmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filtersSheepLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtersSheepComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filtersAlarmLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filtersAlarmCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filtersFilterButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabHome, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabHome, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                    .addComponent(panelFilters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabMain.addTab("Home", panelHome);
        panelHome.getAccessibleContext().setAccessibleName("");

        tabOptions.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabOptionsStateChanged(evt);
            }
        });

        addSheep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addSheepMousePressed(evt);
            }
        });

        addSheepTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addSheepTitleLabel.setText("Add Sheep:");

        addSheepName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addSheepName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSheepNameActionPerformed(evt);
            }
        });

        addSheepNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addSheepNameLabel.setText("Name:");

        addSheepBirthYearLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addSheepBirthYearLabel.setText("Birth year:");

        addSheepFarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSheepFarmActionPerformed(evt);
            }
        });

        addSheepFarmLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addSheepFarmLabel.setText("Farm:");

        addSheepBirthYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));

        addSheepNameOptionalLabel.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        addSheepNameOptionalLabel.setText("(Optional)");

        addSheepAdd.setText("Add Sheep");
        addSheepAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSheepAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addSheepLayout = new javax.swing.GroupLayout(addSheep);
        addSheep.setLayout(addSheepLayout);
        addSheepLayout.setHorizontalGroup(
            addSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSheepLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(addSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSheepTitleLabel)
                    .addGroup(addSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(addSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addSheepBirthYearLabel)
                            .addComponent(addSheepFarmLabel)
                            .addGroup(addSheepLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(addSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addSheepBirthYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addSheepFarm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addSheepAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                        .addGroup(addSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addSheepLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(addSheepName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addSheepLayout.createSequentialGroup()
                                .addComponent(addSheepNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addSheepNameOptionalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        addSheepLayout.setVerticalGroup(
            addSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSheepLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(addSheepTitleLabel)
                .addGap(51, 51, 51)
                .addGroup(addSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSheepNameLabel)
                    .addComponent(addSheepNameOptionalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSheepName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addSheepBirthYearLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSheepBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(addSheepFarmLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSheepFarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addSheepAdd)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        tabOptions.addTab("Add Sheep", addSheep);

        removeSheepTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        removeSheepTitleLabel.setText("Remove Sheep:");

        removeSheepID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeSheepID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSheepIDActionPerformed(evt);
            }
        });

        removeSheepIDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeSheepIDLabel.setText("Sheep ID:");

        removeSheepRemove.setText("Remove Sheep");
        removeSheepRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSheepRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeSheepLayout = new javax.swing.GroupLayout(removeSheep);
        removeSheep.setLayout(removeSheepLayout);
        removeSheepLayout.setHorizontalGroup(
            removeSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeSheepLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(removeSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeSheepLayout.createSequentialGroup()
                        .addComponent(removeSheepIDLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(removeSheepLayout.createSequentialGroup()
                        .addGroup(removeSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeSheepTitleLabel)
                            .addGroup(removeSheepLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(removeSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(removeSheepRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(removeSheepID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 380, Short.MAX_VALUE))))
        );
        removeSheepLayout.setVerticalGroup(
            removeSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeSheepLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(removeSheepTitleLabel)
                .addGap(50, 50, 50)
                .addComponent(removeSheepIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeSheepID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeSheepRemove)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        tabOptions.addTab("Remove Sheep", removeSheep);

        addFarmTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addFarmTitleLabel.setText("Add Farm:");

        addFarmName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        addFarmNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addFarmNameLabel.setText("Farm Name:");

        addFarmAdd.setText("Add Farm");
        addFarmAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFarmAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addFarmLayout = new javax.swing.GroupLayout(addFarm);
        addFarm.setLayout(addFarmLayout);
        addFarmLayout.setHorizontalGroup(
            addFarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFarmLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(addFarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addFarmNameLabel)
                    .addComponent(addFarmTitleLabel)
                    .addGroup(addFarmLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(addFarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addFarmAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addFarmName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        addFarmLayout.setVerticalGroup(
            addFarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFarmLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(addFarmTitleLabel)
                .addGap(52, 52, 52)
                .addComponent(addFarmNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addFarmName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addFarmAdd)
                .addContainerGap(365, Short.MAX_VALUE))
        );

        tabOptions.addTab("Add Farm", addFarm);

        removeFarmTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        removeFarmTitleLabel.setText("Remove Farm:");

        removeFarmNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeFarmNameLabel.setText("Farm ID:");

        removeFarmAdd.setText("Remove Farm");
        removeFarmAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFarmAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeFarmLayout = new javax.swing.GroupLayout(removeFarm);
        removeFarm.setLayout(removeFarmLayout);
        removeFarmLayout.setHorizontalGroup(
            removeFarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeFarmLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(removeFarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeFarmLayout.createSequentialGroup()
                        .addComponent(removeFarmNameLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(removeFarmLayout.createSequentialGroup()
                        .addGroup(removeFarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeFarmTitleLabel)
                            .addGroup(removeFarmLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(removeFarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(removeFarmAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(removeFarmComboFarm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 380, Short.MAX_VALUE))))
        );
        removeFarmLayout.setVerticalGroup(
            removeFarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeFarmLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(removeFarmTitleLabel)
                .addGap(50, 50, 50)
                .addComponent(removeFarmNameLabel)
                .addGap(14, 14, 14)
                .addComponent(removeFarmComboFarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeFarmAdd)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        tabOptions.addTab("Remove Farm", removeFarm);

        tabMain.addTab("Options", tabOptions);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSheepNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSheepNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSheepNameActionPerformed

    private void addSheepFarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSheepFarmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSheepFarmActionPerformed

    private void removeSheepIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSheepIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeSheepIDActionPerformed

    private void addFarmAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFarmAddActionPerformed
       String farmName = addFarmName.getText();
       if (farmName.length() >= 3) {
    	   addFarmName.setText(null);
    	   ArrayList<Farm> metadata = new ArrayList<Farm>();
    	   metadata.add(new Farm(-1, farmName, ServerData.owner.getOwnerId()));
    	   Client.sockCli.sendMessage(new CommMessage<Farm>(CommEnum.ADDFARM,metadata));
    	   DbDownload.loadFarms();
       }else{
    	   JOptionPane.showMessageDialog(this, "Farm name must be at least 3 characters", "Invalid name", JOptionPane.ERROR_MESSAGE);
       }
       
    }//GEN-LAST:event_addFarmAddActionPerformed

    private void removeFarmAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFarmAddActionPerformed
        String farmToRemove = (String) this.removeFarmComboFarm.getSelectedItem();
        System.out.print(farmToRemove);
        ArrayList<Farm> metadata = new ArrayList<Farm>();
        metadata.add(ServerData.getFarmByNameAndRemove(farmToRemove));
        Client.sockCli.sendMessage(new CommMessage<Farm>(CommEnum.REMOVEFARM, metadata));
        initRemoveFarm();
    }//GEN-LAST:event_removeFarmAddActionPerformed

    private void addSheepAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSheepAddActionPerformed
        String name = addSheepName.getText();
        int birthYear = Integer.parseInt((String) addSheepBirthYear.getSelectedItem());
        String farmName = (String) addSheepFarm.getSelectedItem();
        addSheepName.setText(null);
        ArrayList<Sheep> sheep = new ArrayList<Sheep>();
        sheep.add(new Sheep(-1, name, birthYear, ServerData.getFarmByName(farmName).getFarmId(), ServerData.owner.getOwnerId()));
        Client.sockCli.sendMessage(new CommMessage<Sheep>(CommEnum.ADDSHEEP, sheep));
    }//GEN-LAST:event_addSheepAddActionPerformed

    private void removeSheepRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSheepRemoveActionPerformed
       int id = Integer.parseInt(removeSheepID.getText());
       removeSheepID.setText(null);
       ArrayList<Sheep> sheep = new ArrayList<Sheep>();
       sheep.add(new Sheep(id, "", -1, -1, -1));
       Client.sockCli.sendMessage(new CommMessage<Sheep>(CommEnum.REMOVESHEEP, sheep));
       
    }//GEN-LAST:event_removeSheepRemoveActionPerformed

    private void addSheepMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSheepMousePressed
        //System.out.println("hurra");
    }//GEN-LAST:event_addSheepMousePressed

    private void tabOptionsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabOptionsStateChanged
        // TODO add your handling code here:
        initAddSheep();
        initRemoveFarm();
    	// Uteldet...
    }//GEN-LAST:event_tabOptionsStateChanged

    private void tabHomeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabHomeStateChanged
        // TODO add your handling code here:
        refreshMessages();
    }//GEN-LAST:event_tabHomeStateChanged

    private void filtersAlarmCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtersAlarmCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtersAlarmCheckBoxActionPerformed

    private void filtersFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtersFilterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtersFilterButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addFarm;
    private javax.swing.JButton addFarmAdd;
    private javax.swing.JTextField addFarmName;
    private javax.swing.JLabel addFarmNameLabel;
    private javax.swing.JLabel addFarmTitleLabel;
    private javax.swing.JPanel addSheep;
    private javax.swing.JButton addSheepAdd;
    private javax.swing.JComboBox addSheepBirthYear;
    private javax.swing.JLabel addSheepBirthYearLabel;
    private javax.swing.JComboBox addSheepFarm;
    private javax.swing.JLabel addSheepFarmLabel;
    private javax.swing.JTextField addSheepName;
    private javax.swing.JLabel addSheepNameLabel;
    private javax.swing.JLabel addSheepNameOptionalLabel;
    private javax.swing.JLabel addSheepTitleLabel;
    private javax.swing.JCheckBox filtersAlarmCheckBox;
    private javax.swing.JLabel filtersAlarmLabel;
    private javax.swing.JComboBox filtersFarmComboBox;
    private javax.swing.JLabel filtersFarmLabel;
    private javax.swing.JButton filtersFilterButton;
    private javax.swing.JLabel filtersLabel;
    private javax.swing.JComboBox filtersSheepComboBox;
    private javax.swing.JLabel filtersSheepLabel;
    private javax.swing.JPanel map;
    private javax.swing.JList messageList;
    private javax.swing.JPanel messages;
    private javax.swing.JPanel panelFilters;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel removeFarm;
    private javax.swing.JButton removeFarmAdd;
    private javax.swing.JComboBox removeFarmComboFarm;
    private javax.swing.JLabel removeFarmNameLabel;
    private javax.swing.JLabel removeFarmTitleLabel;
    private javax.swing.JPanel removeSheep;
    private javax.swing.JTextField removeSheepID;
    private javax.swing.JLabel removeSheepIDLabel;
    private javax.swing.JButton removeSheepRemove;
    private javax.swing.JLabel removeSheepTitleLabel;
    private javax.swing.JTabbedPane tabHome;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTabbedPane tabOptions;
    // End of variables declaration//GEN-END:variables
    

    public void initComp(){
        initAddSheep();
        initRemoveFarm();
        refreshMessages();
    }
    private String[] getFarmNames(){
    	if(ServerData.farms.isEmpty())
    		return new String[] {"You have no farm's"};
        String[] tmp = new String[ServerData.farms.size()];
        for (int i = 0; i < tmp.length; i++) {
			tmp[i] = ServerData.farms.get(i).getName();
		}
        return tmp;
    }

    private void initAddSheep(){
    	addSheepFarm.setModel(new DefaultComboBoxModel(getFarmNames()));
    }
    private void initRemoveFarm() {
        removeFarmComboFarm.setModel(new DefaultComboBoxModel(getFarmNames()));
    }
     private void refreshMessages()
    {
        // send request
        
        if (ServerData.isLoggedIn)
        {
            Client.sockCli.sendMessage(new CommMessage<String>(CommEnum.GETMESSAGES, null));
        
            messageList.setListData(ServerData.messages.toArray());
            messageList.setVisible(true);
        }
    }
}
