package gui;

/**
*
* @author Kyrre
*/
public class Login extends javax.swing.JFrame {

   /**
    * Creates new form Login
    */
   public Login() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

       username = new javax.swing.JTextField();
       labelUser = new javax.swing.JLabel();
       labelPassword = new javax.swing.JLabel();
       password = new javax.swing.JPasswordField();
       labelLogin = new javax.swing.JLabel();
       login = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       username.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               usernameActionPerformed(evt);
           }
       });

       labelUser.setText("Username:");

       labelPassword.setText("Password:");

       labelLogin.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
       labelLogin.setText("Login");

       login.setText("Login");
       login.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               loginActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(72, 72, 72)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(labelPassword)
                           .addComponent(labelUser, javax.swing.GroupLayout.Alignment.LEADING)))
                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                       .addGroup(layout.createSequentialGroup()
                           .addContainerGap()
                           .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                           .addGap(82, 82, 82)
                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                               .addComponent(login)
                               .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                   .addGroup(layout.createSequentialGroup()
                       .addGap(19, 19, 19)
                       .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addContainerGap(78, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(labelLogin)
               .addGap(20, 20, 20)
               .addComponent(labelUser)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(labelPassword)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(login)
               .addContainerGap(47, Short.MAX_VALUE))
       );

       pack();
   }// </editor-fold>

   private void usernameActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
   }

   private void loginActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
       this.setVisible(false);
       GUI.hub.setVisible(true);
   }

   /**
    * @param args the command line arguments
    */

   // Variables declaration - do not modify
   private javax.swing.JLabel labelLogin;
   private javax.swing.JLabel labelPassword;
   private javax.swing.JLabel labelUser;
   private javax.swing.JButton login;
   private javax.swing.JPasswordField password;
   private javax.swing.JTextField username;
   // End of variables declaration
}
