/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import helpclasses.CommEnum;
import helpclasses.CommMessage;
import helpclasses.Owner;

import java.awt.RenderingHints;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;

import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

import client.Client;
import client.ServerData;
import javax.swing.ImageIcon;

/**
 *
 * @author Kyrre
 */
public class Login extends javax.swing.JFrame {

	/**
	 * Creates new form Login
	 */
	public Login() {
		initComponents();
		if(!Client.ServerUp)
			JOptionPane.showMessageDialog(this, "Could not connect to server", "Connection Error", JOptionPane.ERROR_MESSAGE);
           	initComp();
        }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JTextField();
        labelUser = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        registerNewUser = new javax.swing.JButton();
        test = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(290, 200));
        setResizable(false);

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        labelUser.setText("Username:");

        labelPassword.setText("Password:");

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        registerNewUser.setText("Register");
        registerNewUser.setToolTipText("");
        registerNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerNewUserActionPerformed(evt);
            }
        });

        test.setMaximumSize(new java.awt.Dimension(113, 113));
        test.setMinimumSize(new java.awt.Dimension(113, 113));
        test.setPreferredSize(new java.awt.Dimension(113, 113));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPassword)
                    .addComponent(labelUser)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(login)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerNewUser))
                            .addComponent(password)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(login)
                            .addComponent(registerNewUser)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-387)/2, (screenSize.height-194)/2, 387, 194);
    }// </editor-fold>//GEN-END:initComponents

	private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
		// TODO add your handling code here:
		
		String username = this.username.getText();
		String password = this.password.getText();
		if (Client.ServerUp) {
			if (isUsernameAndPassword(username, password)) {
				this.setVisible(false);
				Client.hub.setVisible(true);
				Client.hub.initComp();
			} else
				JOptionPane.showMessageDialog(this,
						"Wrong Username or Password", "Error",
						JOptionPane.ERROR_MESSAGE);
		}else{
			JOptionPane.showMessageDialog(this,
					"You are not connected to the server.\nRestart the client and try again,\nor contact your system administrator", " Connection Error",
					JOptionPane.ERROR_MESSAGE);
		}



	}//GEN-LAST:event_loginActionPerformed

	/**
	 * This method is called when the user hits enter and the marker is in the password field.
	 * It is called so that loginActionPreformed() will get called upon hitting enter.
	 * @author Kyrre 
	 */
	private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
		// TODO add your handling code here:
		if(evt.getKeyCode() == KeyEvent.VK_ENTER)
			loginActionPerformed(null);
	}//GEN-LAST:event_passwordKeyPressed
	
	/**
	 * This method is called when the user clicks Register User and brings up the registerNewUser class in client.Client
	 * @param evt
	 */
    private void registerNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerNewUserActionPerformed
        
    	this.setVisible(false);
        Client.registerNewUser.setVisible(true);
    }//GEN-LAST:event_registerNewUserActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUser;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registerNewUser;
    private javax.swing.JLabel test;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

	/**
	 * This method is called to check if username and password exist in the database
	 * by calling sockCli.sendMessage with the enum LOGIN
	 * @author Kyrre
	 * @param username
	 * @param password
	 * @return
	 */
	private boolean isUsernameAndPassword(String username, String password) {

		if (username.length() == 0 || password.length() == 0)
			return false;

		ArrayList<String> al = new ArrayList<String>();
		al.add(username);
		al.add(password);
		Client.sockCli.sendMessage(new CommMessage<String>(CommEnum.LOGIN, al));
		return client.ServerData.isLoggedIn;
	}
	private void initComp(){
		ImageIcon img = new ImageIcon(getClass().getResource("/res/briller_hatt_liten.png"));
        test.setIcon(img);
        this.setTitle(Client.name + " " + Client.version);
        setIcon();
	}
	private void setIcon(){
		BufferedImage image = null;
		try {
			image = ImageIO.read(
					this.getClass().getResource("/res/briller_hatt.png"));
		} catch (IOException e) {
			e.printStackTrace();
		}
		this.setIconImage(image);
	}
}
